name: appwrite_platform
description: Sample project to show how to use server-side features of AppWrite
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  dart_appwrite: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
